---
- name: Make sure the seerr container is created and running
  community.docker.docker_container:
    name: "jellyseerr"
    image: "ghcr.io/seerr-team/seerr:latest"
    pull: always
    networks:
      - name: app_network
    dns_servers:
      - 1.1.1.1
      - 8.8.8.8
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/seerr:/app/config"
    restart_policy: unless-stopped
