---
- name: Make sure the wizarr container is created and running
  community.docker.docker_container:
    name: 'wizarr'
    image: ghcr.io/wizarrrr/wizarr:latest
    labels: {"nas-setup.service": "wizarr"}
    networks:
      - name: media_network
    pull: "{{ container_pull }}"
    state: 'started'
    volumes:
      - '{{ docker_dir }}/wizarr/database:/data/database'
    restart_policy: unless-stopped
