---
- name: Make sure the audiobookshelf container is created and running
  community.docker.docker_container:
    name: "audiobookshelf"
    image: "ghcr.io/advplyr/audiobookshelf:latest"
    labels: {"nas-setup.service": "audiobookshelf"}
    pull: "{{ container_pull }}"
    networks:
      - name: app_network
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/audiobookshelf/metadata:/metadata"
      - "{{ docker_dir }}/audiobookshelf/config:/config"
      - "{{ mergerfs_root }}/Media/Audiobooks:/audiobooks"
    restart_policy: unless-stopped
