---
network:
  name: wireguard_network

containers:
  - image: linuxserver/wireguard:latest
    networks:
      - name: wireguard_network
    capabilities:
      - net_admin
    ports:
      - "51820:51820"
    volumes:
      - "{{ docker_dir }}/wireguard/config:/config"

  - name: wireguard-ui
    image: ngoduykhanh/wireguard-ui:latest
    networks:
      - name: wireguard_network
      - name: app_network
    capabilities:
      - net_admin
    env:
      WGUI_MANAGE_START: "true"
      WGUI_MANAGE_RESTART: "true"
    volumes:
      - "{{ docker_dir }}/wireguard/db:/app/db"
      - "{{ docker_dir }}/wireguard/config:/etc/wireguard"
