---
- name: Restart relevant services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - netfilter-persistent
    - docker
    # - crowdsec
    # - crowdsec-firewall-bouncer
  register: result
  until: result is succeeded
  retries: 2

- name: Remove the default rules
  ansible.builtin.file:
    path: /etc/iptables/rules.v4
    state: absent
