---
- name: Make sure the homarr container is created and running
  community.docker.docker_container:
    name: 'homarr'
    image: ghcr.io/homarr-labs/homarr:latest
    labels: {"nas-setup.service": "homarr"}
    networks:
      - name: app_network
    pull: "{{ container_pull }}"
    state: 'started'
    env:
      'SECRET_ENCRYPTION_KEY': '{{ homarr_key }}'
    volumes:
      - '{{ docker_dir }}/homarr/appdata:/appdata'
    restart_policy: unless-stopped
