---
- name: Mount the data drives
  ansible.posix.mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
    passno: "2"
  loop: "{{ disks }}"
  when: disks[0] is defined

- name: Mount the cache drives
  ansible.posix.mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    state: mounted
    opts: defaults,discard
    passno: "2"
  loop: "{{ cache_disks }}"
  when: cache_disks[0] is defined

- name: Mount the parity drives
  ansible.posix.mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
    passno: "2"
  loop: "{{ parity_disks }}"
  when: parity_disks[0] is defined

# - name: Mount the mergerfs cached array
#   mount:
#     name: "{{ mergerfs_root }}"
#     src: /mnt/storage_cache:/mnt/storage_slow
#     opts: category.create=lfs,defaults,allow_other,moveonenospc=1,minfreespace=50G,fsname=mergerfs,uid=1000,gid=1000
#     fstype: fuse.mergerfs
#     state: mounted
#   when: disks[0] is defined

- name: Mount the mergerfs array
  ansible.posix.mount:
    name: "{{ mergerfs_root }}"
    src: /mnt/data*
    opts: category.create=lfs,defaults,allow_other,moveonenospc=1,minfreespace=50G,fsname=mergerfs,uid=1000,gid=1000
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined

- name: Mount the mergerfs cache only array
  ansible.posix.mount:
    name: "{{ cache_root }}"
    src: /mnt/cache*
    opts: defaults,allow_other,fsname=mergerfs_cache,category.create=mfs
    fstype: fuse.mergerfs
    state: mounted
  when: cache_disks[0] is defined

# - name: Set owner and permissions of storage
#   file:
#     dest: "{{ mergerfs_root }}"
#     state: directory
#     owner: "{{ username }}"
#     group: "users"
#     mode: "ug=rwx,o=rx,g+s"
#     recurse: yes
