---
docker_deps:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'gnupg'
  # Needed by the "Switch to pip3" alternatives task.
  - 'python3-pip'

docker_packages:
  - 'docker-ce'
  - 'docker-ce-cli'
  - 'containerd.io'
  - 'docker-buildx-plugin'
  - 'docker-compose-plugin'
