---
- name: Create a login user
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password | password_hash }}"
    groups:
      - sudo
      - users
    state: present
    append: true
    update_password: on_create

- name: Ensure the login group exists
  ansible.builtin.group:
    name: "{{ username }}"
    state: present

- name: Ensure group "sambashare" exists
  when: enable_samba | default(False)
  ansible.builtin.group:
    name: "sambashare"
    state: present

- name: Append the samba group
  when: enable_samba | default(False)
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - sambashare
    append: true

- name: Chmod the user home directory
  ansible.builtin.file:
    path: "/home/{{ username }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: false

- name: Allow 'sudo' group to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Copy the public SSH key
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"
  notify:
    - Remove default user

- name: Set the default shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ shell }}"

- name: Suppress login messages
  ansible.builtin.file:
    path: /home/{{ username }}/.hushlogin
    mode: "0644"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve

- name: Disable cron e-mail notifications
  ansible.builtin.cron:
    name: MAILTO
    user: "{{ username }}"
    env: true
    job: ""

- name: Create additional users (no login)
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password | password_hash }}"
    update_password: on_create
    state: present
    append: true
    shell: /sbin/nologin
  loop: "{{ additional_users }}"
  when: additional_users is defined
  no_log: true
