---
- name: Install hd-idle
  ansible.builtin.package:
    name: hd-idle
    state: present

- name: Install the hd-idle configuration file
  ansible.builtin.template:
    src: hd-idle.default.j2
    dest: /etc/default/hd-idle
    owner: root
    group: root
    mode: "0644"

- name: Make sure that hd-idle is started and enabled on boot
  ansible.builtin.systemd:
    name: hd-idle
    state: started
    enabled: true
    masked: false
