---
- name: Create an Tandoor network
  community.docker.docker_network:
    name: tandoor_network


- name: Make sure the Tandoor Postgres container is created and running
  community.docker.docker_container:
    name: "tandoor-postgres"
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    networks:
      - name: tandoor_network
    pull: always
    env:
      POSTGRES_USER: "djangodb"
      POSTGRES_PASSWORD: "{{ tandoor_postgres_password }}"
      POSTGRES_DB: "djangodb"
    volumes:
      - "{{ docker_dir }}/tandoor/db:/var/lib/postgresql/data"
    restart_policy: unless-stopped

- name: Create Tandoor container
  community.docker.docker_container:
    name: tandoor
    image: vabene1111/recipes:latest
    pull: always
    networks:
      - name: app_network
      - name: tandoor_network
    volumes:
      - "{{ docker_dir }}/tandoor/staticfiles:/org/recipies/staticfiles"
      - "{{ docker_dir }}/tandoor/mediafiles:/org/recipies/mediafiles"
    env:
      USER_UID: "{{ guid }}"
      USER_GID: "{{ guid }}"
      SECRET_KEY: "{{ tandoor_secret_key }}"
      DB_ENGINE: "django.db.backends.postgresql"
      POSTGRES_HOST: "tandoor-postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "djangodb"
      POSTGRES_PASSWORD: "{{ tandoor_postgres_password }}"
      POSTGRES_DB: "djangodb"
      ALLOWED_HOSTS: "tandoor.{{ host }}"
    restart_policy: unless-stopped
