---
- name: Schedule a Nextcloud library scan at midnight every day
  ansible.builtin.cron:
    name: Scan the Nextcloud library
    hour: "0"
    minute: "0"
    job: "docker exec nextcloud occ files:scan --all"
