---
- name: Make sure the Watchtower container is created and running
  community.docker.docker_container:
    name: "watchtower"
    image: "nickfedor/watchtower:latest"
    labels: {"nas-setup.service": "watchtower"}
    pull: "{{ container_pull }}"
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
      "WATCHTOWER_SCHEDULE": "{{ watchtower_schedule }}"
      "WATCHTOWER_CLEANUP": "true"
      "WATCHTOWER_INCLUDE_STOPPED": "false"
      "WATCHTOWER_NOTIFICATIONS": "shoutrrr"
      "WATCHTOWER_NOTIFICATIONS_LEVEL": "info"
      "WATCHTOWER_NOTIFICATION_REPORT": "true"
      "WATCHTOWER_NOTIFICATION_URL": >-
        smtp://{{ email_login | urlencode | regex_replace('/', '%2F') }}:{{ email_password | urlencode | regex_replace('/', '%2F') }}@{{ email_smtp_host }}:{{ email_smtp_port_startls }}/?from={{ email | urlencode }}&to={{ email | urlencode }}&auth=Plain&useStartTLS=yes
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped
