---
- name: Make sure the dashdot container is created and running
  community.docker.docker_container:
    name: 'dashdot'
    image: "mauricenino/dashdot"
    labels: {"nas-setup.service": "dashdot"}
    networks:
      - name: app_network
    pull: "{{ container_pull }}"
    state: 'started'
    restart_policy: unless-stopped
