---
- name: Make sure the lidarr container is created and running
  community.docker.docker_container:
    name: "lidarr"
    image: "lscr.io/linuxserver/lidarr:latest"
    pull: always
    networks:
      - name: app_network
    state: 'started'
    dns_servers:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "8686:8686"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/lidarr:/config"
      - "{{ mergerfs_root }}:/tank"
    restart_policy: unless-stopped

- name: Schedule a RSgain scan at 2 AM every day
  ansible.builtin.cron:
    name: Scan the Music library
    hour: "2"
    minute: "0"
    job: "docker run --rm -v {{ mergerfs_root }}/Media/Music:/mnt rsgain easy -S -m MAX /mnt"
