---
- name: Make sure the Flaresolverr container is created and running
  community.docker.docker_container:
    name: "flaresolverr"
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    labels: {"nas-setup.service": "flaresolverr"}
    pull: "{{ container_pull }}"
    networks:
      - name: media_network
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/flaresolverr:/config"
    restart_policy: unless-stopped
