---
- name: Create an invoiceninja network
  community.docker.docker_network:
    name: invoiceninja_network

- name: Create MySQL container for invoiceninja
  community.docker.docker_container:
    name: "invoiceninja-mysql"
    image: "{{ mysql_image }}"
    labels: "{{ watchtower_exclude_labels | combine({'nas-setup.service': 'invoiceninja'}) }}"
    networks:
      - name: invoiceninja_network
    volumes:
      - "{{ docker_dir }}/invoiceninja/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "invoiceninja"
      MYSQL_USER: "invoiceninja"
      MYSQL_PASSWORD: "{{ invoiceninja_db_password }}"
      MYSQL_ROOT_PASSWORD: "{{ invoiceninja_db_root_password }}"
    restart_policy: unless-stopped

- name: Create InvoiceNinja container
  community.docker.docker_container:
    name: invoiceninja
    image: invoiceninja/invoiceninja:latest
    labels: {"nas-setup.service": "invoiceninja"}
    pull: "{{ container_pull }}"
    networks:
      - name: app_network
      - name: invoiceninja_network
    volumes:
      - "{{ docker_dir }}/invoiceninja/public:/var/app/public"
      - "{{ docker_dir }}/invoiceninja/storage:/var/app/storage"
    env:
      USER_UID: "1000"
      USER_GID: "1000"
      APP_ENV: "production"
      APP_DEBUG: "0"
      APP_URL: "https://invoiceninja.{{ host }}"
      APP_KEY: "{{ invoiceninja_app_key }}"
      APP_CIPHER: "AES-256-CBC"
      DB_TYPE: "mysql"
      DB_STRICT: "false"
      DB_HOST: "invoiceninja-mysql"
      DB_DATABASE: "invoiceninja"
      DB_USERNAME: "invoiceninja"
      DB_PASSWORD: "{{ invoiceninja_db_password }}"
    restart_policy: unless-stopped
