---
- name: Create a gitea network
  community.docker.docker_network:
    name: gitea_network

- name: Create MySQL container for Gitea
  community.docker.docker_container:
    name: "gitea-mysql"
    image: "{{ mysql_image }}"
    labels: "{{ watchtower_exclude_labels | combine({'nas-setup.service': 'gitea'}) }}"
    networks:
      - name: gitea_network
    volumes:
      - "{{ docker_dir }}/gitea/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "gitea"
      MYSQL_USER: "gitea"
      MYSQL_PASSWORD: "{{ gitea_db_password }}"
      MYSQL_ROOT_PASSWORD: "{{ gitea_db_root_password }}"
    restart_policy: unless-stopped

- name: Create Gitea container
  community.docker.docker_container:
    name: gitea
    image: gitea/gitea:latest
    labels: {"nas-setup.service": "gitea"}
    pull: "{{ container_pull }}"
    networks:
      - name: gitea_network
    volumes:
      - "{{ docker_dir }}/gitea/data:/data"
    ports:
      - "222:22"
    env:
      DB_TYPE: "mysql"
      DB_HOST: "gitea-mysql:3306"
      DB_NAME: "gitea"
      DB_USER: "gitea"
      DB_PASSWD: "{{ gitea_db_password }}"
      RUN_MODE: "prod"
      USER_UID: "1000"
      USER_GID: "1000"
      DISABLE_REGISTRATION: "true"
      DEFAULT_THEME: "arc-green"
    restart_policy: unless-stopped
